### ISSUE TITLE
Some cases of operationaldata.neos.com aren't captured

### ISSUE THREAD

**Issue by iamgreaser** [Lexevolution/Cloud-Change#2]
In light of recent updates to the Neos wiki I've been trying to work out how to make a custom cloud and have been shoving things into mitmproxy. It turns out that world thumbnails still like to insist on using this endpoint. (It also appears that Neos mostly ignores the `HTTP_PROXY` and `HTTPS_PROXY` env vars, except for thumbnails.)

Note that I am currently using 1.0.0, but I'm not sure if 1.0.1 actually makes everything use the config-provided URLs or if it still bypasses them.

... it also turns out that some cloud fetches do `https://cloudxoperationalblob.blob.core.windows.net/thumbnails000000...0000-v2.webp` (replacing the `0`s with an actual valid UUID of course). The config variables all have a trailing `/` so I'm inclined to believe that this is the engine being high-quality and properly tested when it comes to cloud stuff. *sighs*

**Comment by Lexevolution** [comment]
Here's the main changes I made for 1.0.1: https://github.com/Lexevolution/Cloud-Change/commit/f5a026e2e4f53d4ae3bdd61cc2e71a0df2ff5420. I'm not 100% sure what you're trying to point out though, so I'll go through my thought process.

- This mod was made when the cloudflare proxied urls no longer worked, and the update the Neos Team pushed was extremely rushed (hence thumbnails not working due to them missing a slash in the url).
- This mod was updated when the cloudflare urls were fixed, and was switched back to the original cloudflare urls that have been in the same version this whole time (up until the cloudflare issue on the 1st of April).
- Since all the versions released during that time were meant to be network compatible, they used the same compatibility hash and version number. This I think has lead to some people not updating their headless servers to the latest with the fully fixed, up-to-date urls. Also the thumbnail url that a client uses is generated from the session host, which means while most people have this issue fixed, some who have not updated, still are sending malformed thumbnail urls. (Could you check to see if the malformed urls you received are only coming from headless clients?).
- I made sure in the config to put the same trailing slashes as the decompiled constants from `CloudX.Shared.dll`, as when I was testing, adding/removing the slashes did affect the urls and whether they worked or not.

**Comment by iamgreaser** [comment]
OK, after being able to get a much better log I've realised that Neos is taking the URLs directly from the API, and thus the different URLs aren't the fault of this mod... and in most cases aren't really a bug either.

I'll close this issue.
